### ISSUE TITLE
asm compile

### ISSUE THREAD

**Issue by krzysiek841** [dpiegdon/SainSmart-REY-NET-v1.1#1]
Hello. What software (windows based) do you use to compile asm to bin ? I want to set other ip and mac. Thanks ;)

**Comment by dpiegdon** [comment]
Hi!
Sorry, I don't think there is a software to recompile the provided flash.asm into a binary. This ASM was only generated for reverse-engineering.
I did edit the IP by editing the raw memory locations in the BIN file with a hexeditor.
Please refer to section "Fixing IP and MAC addresses" in the README of this repo if you want to try it.
