### ISSUE TITLE
Serial firmware recovery?

### ISSUE THREAD

**Issue by joquers** [dpiegdon/SainSmart-REY-NET-v1.1#2]
Hi, I have 2 of controllers of these and I stored them since I was no longer using them... then the time came to use them once again and they no longer work :/ (Ethernet orange LED blinks even though there is no cable connected to it)

Is there any way I can flash the firmware back again using a serial TTL adapter?

**Comment by dpiegdon** [comment]
Not sure, but some of the STM32s have a serial bootloader that might be usable for that. But you'd have to set the boot-pins to enable that. Easier to use the SWD interface, as described in the Readme.

**Comment by dpiegdon** [comment]
Doh, sorry. I forgot that they don't use an STM32 but a Nuvoton. No idea about those, so SWD then is the only way I know about.
